# Generated by Django 2.0 on 2019-01-15 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('creation_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 15, 18, 47, 10, 939744, tzinfo=utc))),
            ],
        ),
    ]
