# Generated by Django 2.1.3 on 2019-01-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=400)),
                ('data_publicacao', models.DateTimeField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_postagens', to='perfis.Perfil')),
            ],
        ),
    ]
