# Generated by Django 2.1.4 on 2019-01-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_publicacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
