# Generated by Django 2.1.4 on 2019-01-05 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190105_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 20, 34, 33, 675403)),
        ),
    ]
