# Generated by Django 2.0 on 2019-01-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_auto_20190105_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='contatos_bloqueados',
            field=models.ManyToManyField(related_name='meus_contatos_bloqueados', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='bloqueado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueado', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='bloqueador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueador', to='perfis.Perfil'),
        ),
    ]
