# Generated by Django 2.1.5 on 2019-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfis'),
        ),
    ]
